/* Program to calculate the area of ractangle
   By Shobhit Kumar Patkar
   email-cs1938@global.org.in
*/

 #include<stdio.h>
 #include<conio.h>

 void main()
 {
 float lnth,brth,area;
 clrscr();

 printf("Enter the length \n");
 scanf("%f",&lnth);

 printf("\nEnter the breadth \n");
 scanf("%f",&brth);

 area=lnth*brth;

 printf("\nArea of ractangle is %f square units",area);
 getch();

 }








